# AIUnblock RU — штатные резолверы Smart DNS
# Формат: ПРОТОКОЛ АДРЕС
# Поддерживаемые записи: DOH, DOT, DNS.

DOH https://dns.malw.link/dns-query
DOT dns.malw.link
DNS 95.216.204.218
DNS 80.253.249.40

DOH https://xbox-dns.ru/dns-query
DOT xbox-dns.ru
DNS 111.88.96.50
DNS 111.88.96.51

DOH https://dns.geohide.ru/dns-query
DOT dns.geohide.ru
DNS 45.155.204.190
DNS 37.230.192.51
DNS 95.182.120.241
