# ==============================================================================
# zapret2-android WebUI BusyBox httpd config
# ==============================================================================
*.sh:/system/bin/sh
*.cgi:/system/bin/sh
