SKIPUNZIP=0

DATA_DIR="/data/adb/analytics_ads_disabler"
SETTINGS_FILE="$DATA_DIR/settings.conf"
CAPABILITIES_FILE="$DATA_DIR/capabilities.conf"
[ -f "$MODPATH/compat.sh" ] && . "$MODPATH/compat.sh"

ui_print "***********************************************"
ui_print "* Systemwide Analytics & Ads Disabler        *"
ui_print "* v4.2.0 Runtime Adaptive Edition             *"
ui_print "* Author: eCubz (https://t.me/eCubz)         *"
ui_print "***********************************************"

if [ "$KSU" = "true" ]; then
  ROOT_MANAGER="KernelSU"
elif [ "$APATCH" = "true" ] || [ "$KERNELPATCH" = "true" ]; then
  ROOT_MANAGER="APatch"
else
  ROOT_MANAGER="Magisk"
fi
ui_print "- Root manager: $ROOT_MANAGER"
ui_print "- Android API: ${API:-unknown} | ABI: ${ARCH:-unknown}"

# Returns 0 for Vol+, 1 for Vol-. If getevent is unavailable, returns the supplied default.
volume_select() {
  default_answer="$1"
  if ! command -v getevent >/dev/null 2>&1; then
    ui_print "! getevent unavailable; using default selection."
    [ "$default_answer" = "yes" ] && return 0
    return 1
  fi

  while true; do
    if command -v timeout >/dev/null 2>&1; then
      event="$(timeout 30 getevent -qlc 1 2>/dev/null)"
      if [ -z "$event" ]; then
        ui_print "! No volume-key event; using recommended default."
        [ "$default_answer" = "yes" ] && return 0
        return 1
      fi
    else
      event="$(getevent -qlc 1 2>/dev/null)"
    fi
    echo "$event" | grep -q "KEY_VOLUMEUP.*DOWN" && return 0
    echo "$event" | grep -q "KEY_VOLUMEDOWN.*DOWN" && return 1
  done
}

ask_yes_no() {
  prompt="$1"
  recommended="$2"
  ui_print " "
  ui_print "$prompt"
  ui_print "  VOL+ = YES    VOL- = NO"
  [ -n "$recommended" ] && ui_print "  Recommended: $recommended"
  if volume_select "$( [ "$recommended" = "YES" ] && echo yes || echo no )"; then
    ui_print "  -> YES"
    return 0
  fi
  ui_print "  -> NO"
  return 1
}

mkdir -p "$DATA_DIR"
chmod 700 "$DATA_DIR" 2>/dev/null

KEEP_EXISTING=0
if [ -f "$SETTINGS_FILE" ]; then
  ui_print " "
  ui_print "- Existing v4 settings detected."
  ui_print "  Keep current choices?"
  ui_print "  VOL+ = KEEP    VOL- = RECONFIGURE"
  if volume_select yes; then
    KEEP_EXISTING=1
    ui_print "  -> Keeping current settings"
  else
    ui_print "  -> Reconfiguring"
  fi
fi

if [ "$KEEP_EXISTING" -eq 0 ]; then
  BLOCK_ANALYTICS=0
  BLOCK_ADS=0
  SCAN_ALL_USERS=0
  SCAN_SYSTEM_APPS=0

  ask_yes_no "Disable ANALYTICS / tracking components?" "YES" && BLOCK_ANALYTICS=1
  ask_yes_no "Disable ADVERTISING components?" "YES" && BLOCK_ADS=1
  ask_yes_no "Scan ALL Android users/profiles?" "YES" && SCAN_ALL_USERS=1
  ask_yes_no "Scan SYSTEM apps too?" "NO" && SCAN_SYSTEM_APPS=1

  cat > "$SETTINGS_FILE" <<CFG
# Analytics & Ads Disabler v4 — runtime settings
# Generated by installer. You can edit this file later as root.
BLOCK_ANALYTICS=$BLOCK_ANALYTICS
BLOCK_ADS=$BLOCK_ADS
SCAN_ALL_USERS=$SCAN_ALL_USERS
SCAN_SYSTEM_APPS=$SCAN_SYSTEM_APPS
REALTIME_MONITOR=1
CATEGORY_POLL_INTERVAL=10
PACKAGE_POLL_INTERVAL=60
PACKAGE_SAFETY_POLL_INTERVAL=900
MAX_MATCHES_PER_CATEGORY=15
CFG
  chmod 600 "$SETTINGS_FILE" 2>/dev/null
fi

# Add new runtime defaults on upgrades without overwriting existing user choices.
for kv in 'PACKAGE_POLL_INTERVAL=60' 'PACKAGE_SAFETY_POLL_INTERVAL=900'; do
  key=${kv%%=*}
  if ! grep -q "^[[:space:]]*$key[[:space:]]*=" "$SETTINGS_FILE" 2>/dev/null; then
    echo "$kv" >> "$SETTINGS_FILE"
  fi
done

# Probe this ROM once and persist the selected command/profile.
ui_print " "
ui_print "- Detecting device command capabilities..."
probe_capabilities
if ! cap_profile_valid; then
  abort "! Required Android package-manager capabilities were not detected safely."
fi
load_capabilities
ui_print "  Disable : $CAP_PM_DISABLE_BACKEND package $CAP_PM_DISABLE_VERB (user=$CAP_PM_DISABLE_HAS_USER)"
ui_print "  Enable  : $CAP_PM_ENABLE_BACKEND package $CAP_PM_ENABLE_VERB (user=$CAP_PM_ENABLE_HAS_USER)"
ui_print "  Default : $CAP_PM_DEFAULT_BACKEND package $CAP_PM_DEFAULT_VERB (user=$CAP_PM_DEFAULT_HAS_USER)"
ui_print "  Restore disabled: $CAP_PM_STATE_DISABLED_BACKEND package $CAP_PM_STATE_DISABLED_VERB (exact=$CAP_PM_STATE_DISABLED_EXACT)"
ui_print "  Probe   : runtime missing-component validation"
ui_print "  Users   : $CAP_USER_LIST_BACKEND"
ui_print "  Packages: $CAP_PACKAGE_LIST_BACKEND (user=$CAP_PACKAGE_LIST_HAS_USER, versionCode=$CAP_PACKAGE_LIST_HAS_VERSIONCODE)"
ui_print "  Dump    : $CAP_PACKAGE_DUMP_BACKEND"
ui_print "  Watcher : $CAP_APP_WATCH_BACKEND"
SCAN_ALL_USERS_EFFECTIVE=$(sed -n 's/^[[:space:]]*SCAN_ALL_USERS[[:space:]]*=[[:space:]]*//p' "$SETTINGS_FILE" | head -n1 | tr -d '\r')
[ -n "$SCAN_ALL_USERS_EFFECTIVE" ] || SCAN_ALL_USERS_EFFECTIVE=1
if [ "$SCAN_ALL_USERS_EFFECTIVE" = "1" ] && { [ "$CAP_PM_DISABLE_HAS_USER" != "1" ] || [ "$CAP_PM_ENABLE_HAS_USER" != "1" ] || [ "$CAP_PM_DEFAULT_HAS_USER" != "1" ] || [ "$CAP_PACKAGE_LIST_HAS_USER" != "1" ]; }; then
  ui_print "! This ROM lacks complete --user support; runtime will safely use user 0 only."
fi

# Preserve user configuration across module updates. Defaults are copied only on first install.
for f in rules.conf whitelist.list white_ads.list white_analytics.list; do
  if [ ! -f "$DATA_DIR/$f" ] && [ -f "$MODPATH/$f" ]; then
    cp "$MODPATH/$f" "$DATA_DIR/$f"
  fi
done

# Migrate the old state format safely: old v3 state did not preserve user IDs/original states,
# so it must not be trusted for exact rollback in v4. Keep a backup for diagnostics.
if [ -s "$DATA_DIR/disabled_components.list" ] && ! grep -q '^[0-9][0-9]*|' "$DATA_DIR/disabled_components.list" 2>/dev/null; then
  cp "$DATA_DIR/disabled_components.list" "$DATA_DIR/disabled_components.v3.backup" 2>/dev/null
  ui_print "- Legacy v3 state found; resetting its user-0 overrides before migration..."
  while IFS='|' read -r oldcomp oldcat; do
    [ -z "$oldcomp" ] && continue
    cap_set_component_state 0 "$oldcomp" default >/dev/null 2>&1
  done < "$DATA_DIR/disabled_components.list"
  : > "$DATA_DIR/disabled_components.list"
  rm -f "$DATA_DIR/component_state.list" "$DATA_DIR/package_state.list"
  ui_print "- Migrated legacy v3 state (backup kept in data directory)."
fi

set_perm "$MODPATH/common.sh" 0 0 0644
set_perm "$MODPATH/compat.sh" 0 0 0644
set_perm "$MODPATH/service.sh" 0 0 0755
set_perm "$MODPATH/on_app_installed.sh" 0 0 0755
set_perm "$MODPATH/config_watch.sh" 0 0 0755
set_perm "$MODPATH/category_watch.sh" 0 0 0755
set_perm "$MODPATH/action.sh" 0 0 0755
set_perm "$MODPATH/uninstall.sh" 0 0 0755

ui_print " "
ui_print "- Installation complete. Compatibility profile saved."
ui_print "- Safe scanner: Services + Receivers only; no Activity/Provider fallback."
ui_print "- Original component state is preserved per Android user."
ui_print "- Config survives module updates: $DATA_DIR"
ui_print "- Use the module Action button for a manual full rescan."
